local AbilityConfig = {}

AbilityConfig.Abilities = {
    Gojo_Blue = {
        Id = "Gojo_Blue",
        Clan = "Gojo",
        Name = "Blue",
        Key = "1",
        FocusCost = 20,
        BaseDamage = 24,
        Cooldown = 5,
        MasteryRequirement = 0,
        Type = "Cursed",
        Range = 30,
        Execution = "AttractionBurst",
        PullForce = 95,
        StunDuration = 0.25,
        CastTime = 0.42,
    },
    Gojo_Red = {
        Id = "Gojo_Red",
        Clan = "Gojo",
        Name = "Red",
        Key = "2",
        FocusCost = 35,
        BaseDamage = 35,
        Cooldown = 8,
        MasteryRequirement = 45,
        Type = "Cursed",
        Range = 28,
        Execution = "RepulseBurst",
        KnockbackForce = 120,
        StunDuration = 0.45,
        CastTime = 0.38,
    },
    Gojo_Purple = {
        Id = "Gojo_Purple",
        Clan = "Gojo",
        Name = "Hollow Purple",
        Key = "3",
        FocusCost = 70,
        BaseDamage = 70,
        Cooldown = 18,
        MasteryRequirement = 110,
        Type = "Special",
        Range = 75,
        Execution = "EraseBeam",
        BeamRadius = 9,
        CastTime = 1.0,
    },
    Zenin_TenShadows = {
        Id = "Zenin_TenShadows",
        Clan = "Zenin",
        SubTechnique = "Ten Shadows",
        Name = "Divine Dogs",
        Key = "1",
        FocusCost = 18,
        BaseDamage = 20,
        Cooldown = 5,
        MasteryRequirement = 0,
        Type = "Special",
        Range = 20,
        Execution = "Damage",
    },
    Zenin_Projection = {
        Id = "Zenin_Projection",
        Clan = "Zenin",
        SubTechnique = "Projection Sorcery",
        Name = "Frame Lock",
        Key = "2",
        FocusCost = 22,
        BaseDamage = 18,
        Cooldown = 6,
        MasteryRequirement = 30,
        Type = "Physical",
        Range = 14,
        Execution = "StunDamage",
        StunDuration = 1.5,
    },
    Zenin_Heavenly = {
        Id = "Zenin_Heavenly",
        Clan = "Zenin",
        SubTechnique = "Heavenly Restriction",
        Name = "Heaven Splitter",
        Key = "3",
        FocusCost = 0,
        BaseDamage = 32,
        Cooldown = 7,
        MasteryRequirement = 65,
        Type = "Physical",
        Range = 12,
        Execution = "Damage",
    },
    Itadori_DivergentFist = {
        Id = "Itadori_DivergentFist",
        Clan = "Itadori",
        Name = "Divergent Fist",
        Key = "1",
        FocusCost = 15,
        BaseDamage = 22,
        Cooldown = 4,
        MasteryRequirement = 0,
        Type = "Physical",
        Range = 12,
        Execution = "Damage",
    },
    Itadori_BlackFlash = {
        Id = "Itadori_BlackFlash",
        Clan = "Itadori",
        Name = "Black Flash",
        Key = "3",
        FocusCost = 40,
        BaseDamage = 42,
        Cooldown = 10,
        MasteryRequirement = 90,
        Type = "Special",
        Range = 10,
        Execution = "BlackFlash",
        TimingWindowMin = 0.15,
        TimingWindowMax = 0.35,
        BlackFlashDamageMultiplier = 1.5,
    },
    Fushiguro_Nue = {
        Id = "Fushiguro_Nue",
        Clan = "Fushiguro",
        Name = "Nue",
        Key = "1",
        FocusCost = 18,
        BaseDamage = 20,
        Cooldown = 5,
        MasteryRequirement = 0,
        Type = "Cursed",
        Range = 24,
        Execution = "Damage",
    },
    Kamo_PiercingBlood = {
        Id = "Kamo_PiercingBlood",
        Clan = "Kamo",
        Name = "Piercing Blood",
        Key = "1",
        FocusCost = 16,
        HealthCost = 5,
        BaseDamage = 26,
        Cooldown = 5,
        MasteryRequirement = 0,
        Type = "Cursed",
        Range = 28,
        Execution = "Damage",
    },
    Kamo_Supernova = {
        Id = "Kamo_Supernova",
        Clan = "Kamo",
        Name = "Supernova",
        Key = "3",
        FocusCost = 35,
        HealthCost = 12,
        BaseDamage = 38,
        Cooldown = 9,
        MasteryRequirement = 75,
        Type = "Special",
        Range = 20,
        Execution = "Damage",
    },
    Commoner_Strike = {
        Id = "Commoner_Strike",
        Clan = "Commoner",
        Name = "Focused Strike",
        Key = "1",
        FocusCost = 10,
        BaseDamage = 16,
        Cooldown = 4,
        MasteryRequirement = 0,
        Type = "Physical",
        Range = 10,
        Execution = "Damage",
    },
}

AbilityConfig.AbilitySets = {
    Gojo = { "Gojo_Blue", "Gojo_Red", "Gojo_Purple" },
    Zenin = {
        ["Ten Shadows"] = { "Zenin_TenShadows" },
        ["Projection Sorcery"] = { "Zenin_Projection" },
        ["Heavenly Restriction"] = { "Zenin_Heavenly" },
    },
    Itadori = { "Itadori_DivergentFist", "Itadori_BlackFlash" },
    Fushiguro = { "Fushiguro_Nue" },
    Kamo = { "Kamo_PiercingBlood", "Kamo_Supernova" },
    Commoner = { "Commoner_Strike" },
}

return AbilityConfig
