local AttributeConfig = {}

AttributeConfig.Defaults = {
    Health = 100,
    MaxHealth = 100,
    Focus = 100,
    MaxFocus = 100,
    Clan = "Commoner",
    SubTechnique = "",
    ZeninType = "",
    Mastery = 0,
    Level = 1,
    XP = 0,
    XPToNextLevel = 500,
    Strength = 0,
    Spins = 5,
    ClanLegendaryPity = 0,
    ClanEpicPity = 0,
    Yen = 0,
    Fragments = 0,
    WitnessedDomain = false,
    HasDomain = false,
    DomainActive = false,
    DomainCooldown = 0,
    EnchantedMode = false,
    IsAlive = false,
    IsStunned = false,
    DomainLocked = false,
    CooldownStates = "{}",
    HasStarted = false,
    Rank = "Grade 4",
    ProgressionPhase = "Iniciante",
    Faction = "Unaffiliated",
    CanChooseFaction = false,
    ActiveMissionId = "",
    ActiveMissionProgress = 0,
    ActiveMissionGoal = 0,
    ActiveMissionName = "",
    ActiveMissionCategory = "",
    ActiveMissionRewardXP = 0,
    ActiveMissionRewardYen = 0,
    ActiveMissionRewardFragments = 0,
}

AttributeConfig.PersistedKeys = {
    "Clan",
    "SubTechnique",
    "ZeninType",
    "Level",
    "XP",
    "Mastery",
    "Spins",
    "ClanLegendaryPity",
    "ClanEpicPity",
    "Yen",
    "Fragments",
    "WitnessedDomain",
    "Strength",
    "Rank",
    "Faction",
    "ActiveMissionId",
    "ActiveMissionProgress",
}

AttributeConfig.Required = {
    "Health",
    "MaxHealth",
    "Focus",
    "MaxFocus",
    "Clan",
    "ZeninType",
    "Mastery",
    "Level",
    "XPToNextLevel",
    "HasDomain",
    "DomainActive",
    "DomainCooldown",
    "WitnessedDomain",
    "EnchantedMode",
    "IsAlive",
    "IsStunned",
    "CooldownStates",
    "Rank",
    "ProgressionPhase",
    "Faction",
    "ClanLegendaryPity",
    "ClanEpicPity",
    "Yen",
    "Fragments",
}

return AttributeConfig
