local MissionConfig = {}

MissionConfig.BoardPools = {
    Beginner = {
        {
            Id = "beginner_training_board",
            Category = "Daily",
            Name = "Rotina de Treinamento",
            Type = "Train",
            Goal = 12,
            RewardXP = 650,
            RewardYen = 700,
            RewardFragments = 0,
        },
        {
            Id = "beginner_first_exorcism",
            Category = "Side",
            Name = "Primeiro Exorcismo",
            Type = "DefeatTarget",
            Goal = 4,
            RewardXP = 900,
            RewardYen = 1200,
            RewardFragments = 0,
        },
        {
            Id = "beginner_energy_control",
            Category = "Daily",
            Name = "Controle de Energia Maldita",
            Type = "UseAbility",
            Goal = 8,
            RewardXP = 800,
            RewardYen = 950,
            RewardFragments = 0,
        },
    },
    Student = {
        {
            Id = "student_combat_drill",
            Category = "Daily",
            Name = "Treino de Combate",
            Type = "DealDamage",
            Goal = 450,
            RewardXP = 2400,
            RewardYen = 1800,
            RewardFragments = 0,
        },
        {
            Id = "student_patrol",
            Category = "Side",
            Name = "Patrulha em Shibuya",
            Type = "DefeatTarget",
            Goal = 8,
            RewardXP = 3200,
            RewardYen = 2600,
            RewardFragments = 0,
        },
        {
            Id = "student_form_refinement",
            Category = "Daily",
            Name = "Refino Tecnico",
            Type = "UseAbility",
            Goal = 18,
            RewardXP = 2800,
            RewardYen = 2100,
            RewardFragments = 0,
        },
    },
    Veteran = {
        {
            Id = "veteran_barrier_pressure",
            Category = "Side",
            Name = "Pressao na Barreira",
            Type = "DealDamage",
            Goal = 1800,
            RewardXP = 7200,
            RewardYen = 5400,
            RewardFragments = 1,
        },
        {
            Id = "veteran_field_exorcism",
            Category = "Daily",
            Name = "Exorcismo de Campo",
            Type = "DefeatTarget",
            Goal = 14,
            RewardXP = 6800,
            RewardYen = 5000,
            RewardFragments = 0,
        },
        {
            Id = "veteran_weapon_training",
            Category = "Daily",
            Name = "Treinamento de Resistência",
            Type = "Train",
            Goal = 28,
            RewardXP = 5400,
            RewardYen = 3600,
            RewardFragments = 0,
        },
    },
    Elite = {
        {
            Id = "elite_incident_response",
            Category = "Side",
            Name = "Resposta a Incidente Especial",
            Type = "DefeatTarget",
            Goal = 18,
            RewardXP = 18000,
            RewardYen = 12000,
            RewardFragments = 1,
        },
        {
            Id = "elite_reinforcement_cycle",
            Category = "Daily",
            Name = "Ciclo de Reforco",
            Type = "UseAbility",
            Goal = 26,
            RewardXP = 15500,
            RewardYen = 9800,
            RewardFragments = 0,
        },
        {
            Id = "elite_purge_operation",
            Category = "Side",
            Name = "Operacao de Purga",
            Type = "DealDamage",
            Goal = 4200,
            RewardXP = 21000,
            RewardYen = 13500,
            RewardFragments = 2,
        },
    },
    Legendary = {
        {
            Id = "legendary_collapse_front",
            Category = "Side",
            Name = "Frente do Colapso",
            Type = "DealDamage",
            Goal = 9000,
            RewardXP = 54000,
            RewardYen = 32000,
            RewardFragments = 3,
        },
        {
            Id = "legendary_hunt",
            Category = "Daily",
            Name = "Cacada de Classe",
            Type = "DefeatTarget",
            Goal = 24,
            RewardXP = 50000,
            RewardYen = 28000,
            RewardFragments = 2,
        },
    },
    Transcendent = {
        {
            Id = "transcendent_barrier_break",
            Category = "Side",
            Name = "Quebra de Barreira Global",
            Type = "DealDamage",
            Goal = 14000,
            RewardXP = 125000,
            RewardYen = 60000,
            RewardFragments = 5,
        },
        {
            Id = "transcendent_final_purge",
            Category = "Daily",
            Name = "Purga Transcendente",
            Type = "DefeatTarget",
            Goal = 30,
            RewardXP = 98000,
            RewardYen = 50000,
            RewardFragments = 4,
        },
    },
}

MissionConfig.SpecialMissions = {
    {
        Id = "special_domain_witness",
        Category = "Special",
        Name = "Testemunhe um Dominio",
        Type = "WitnessDomain",
        Goal = 1,
        RewardXP = 24000,
        RewardYen = 18000,
        RewardFragments = 2,
        MinLevel = 81,
        RequiresUnwitnessedDomain = true,
    },
}

return MissionConfig
